// -*- c++ -*-

#ifndef __pqMaskFieldPanel_h
#define __pqMaskFieldPanel_h

// Qt Includes.
#include <QCheckBox>
#include <QComboBox>
#include <QLabel>
#include <QWidget>
#include <QtDebug>

// ParaView Includes.
#include <pqAutoGeneratedObjectPanel.h>
#include <pqComboBoxDomain.h>
#include <vtkPVConfig.h>


/// Custom panel for SuperquadricTensorGlyph filter.
/// This panel is only provided to add capabilities to hide/gray out
/// GUI elements in case they do not apply and to link the checkbox
/// FixedThetaPhiRoundness to GammaRoundness/ThetaRoundness/PhiRoundness.
class pqSymToGenMatrixPanel : public pqAutoGeneratedObjectPanel
{
  Q_OBJECT;
  typedef pqAutoGeneratedObjectPanel Superclass;

public:
  pqSymToGenMatrixPanel(pqProxy *proxy, QWidget *p);

private:


protected slots:

};

#endif //__pqMaskFieldPanel_h
